FROM python:3.9-slim-buster

WORKDIR /app2

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install simple-websocket

COPY . .

ENV FLASK_RUN_HOST=0.0.0.0

EXPOSE 5001

CMD ["python3", "app2.py"]